### ISSUE TITLE
Unbounded memory growth on stream data

### ISSUE THREAD

**Issue by pipijajko** [markNZed/ARTimeNAB.jl#2]
Hi @markNZed 
Congrats on taking the top spot in NAB! Your contribution pointed my interest towards this entirely new (to me) area of neuroscience, for which you have my sincerest thanks.

I took ARTime for a spin, and wanted to see how it fares in a streaming scenario (i.e. ~infinite series), but I noticed something which slightly worries me:
It seems that the internal DVFA structures are growing without any limits.

Please take a look at this snippet:
```
julia> using ARTime, Random, Distributions
julia> Random.seed!(123)

julia> p = ARTime.P(); ARTime.init(-2,2,210000,p)
julia> size(p.cs.art.W)[1] * size(p.cs.art.W)[2]  + size(p.cs.art.M)[1] + size(p.cs.art.Me)[1]
0 #Size before any processing

# Let's say we have a slightly noise sine wave
julia> for x in range(0, 200π, length=10000) 
    y = sin(x) + 0.1 * randn() 
    ARTime.process_sample!(y, p)
end


julia> size(p.cs.art.W)[1] * size(p.cs.art.W)[2]  + size(p.cs.art.M)[1] + size(p.cs.art.Me)[1]
2788  # Internal struct size after 10K points

# Now there's a longer period where the noise more pronounced
julia> for x in range(0, 2000π, length=100000) 
    y = sin(x) + 0.2 * randn()
    ARTime.process_sample!(y, p)
end 

julia> size(p.cs.art.W)[1] * size(p.cs.art.W)[2]  + size(p.cs.art.M)[1] + size(p.cs.art.Me)[1]
27336 # Internal struct size after 110K points

# Noise-levels are down, but the frequency of sine wave has changed
julia>  for x in range(0, 200π, length=100000) 
    y = sin(x) + 0.1 * randn() 
    ARTime.process_sample!(y, p)
end 

julia> size(p.cs.art.W)[1] * size(p.cs.art.W)[2]  + size(p.cs.art.M)[1] + size(p.cs.art.Me)[1]
237422 # Internal struct size after 210K points

julia> p.cs.art.n_categories
6983

julia> p.cs.art.n_clusters
739
```
(I'm aware that there are more internal state variables than W, M, Me, but they grow at similar pace so I omitted them here)

I know that this example is a bit nasty, but this is just to illustrate something that I also see on my real data i.e., that with enough time, the ARTime process will eventually run out of memory and crash (which is not the case for e.g., HTM). It seems that the DVFA never ceases to create new clusters and categories. 

Is this an intentional behavior (or  maybe some sort of optimization for NAB)? 

Is there any way to limit the memory usage (or e.g., somehow compact the current state) without forgetting catastrophically (i.e. full state reset)? 

I would like the algorithm to keep on adapting to the stream (rather than use learned state) - but it seems to have infinite appetite for memory.

**Comment by markNZed** [comment]
Hi, it is nice to hear that you are interested in ART, creating more visibility for ART in the ML community was a significant motivation for creating ARTime. The implementation could be greatly improved on, there are many concepts in ART that are not implemented in ARTime. 

Regarding the memory consumption, ARTime is performing continuous online learning, so if the streaming data keeps changing, then it will keep learning, and that will keep increasing memory consumption. The number of categories will stabilize if there is a limited range of behavior in the time series. From your example it looks like you are trying to learn significant amounts of random noise, so it will take time to stabilize. NAB time series are relatively short so there was no need to optimize this. 

ARTimeNAB needs to be relatively general to perform well on NAB. It can be tuned to a particular type of streaming data and will perform much better in that case. ARTimeNAB is also assuming the time series is structured as per NAB, so initializing ARTimeNAB is not so obvious because this impacts the size of the sliding window used for downsampling.

In general pre-processing of the data stream will be a critical aspect of getting good performance. Good luck!
